
[project]
name = "clarity-xverse"
description = ""
authors = []
telemetry = true
cache_dir = "./.cache"

[contracts.pox-delegation]
path = "contracts/pox-delegation.clar"
clarity_version = 2
epoch = 2.1

[repl.analysis]
passes = ["check_checker"]
check_checker = { trusted_sender = false, trusted_caller = false, callee_filter = false }
