[project]
name = 'clarity-xverse'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'

[[project.requirements]]
contract_id = 'SP000000000000000000002Q6VF78.pox-2'

[[project.requirements]]
contract_id = 'SPDBEG5X8XD50SPM1JJH0E5CTXGDV5NJTKAKKR5V.sip013-semi-fungible-token-trait'

[[project.requirements]]
contract_id = 'SPDBEG5X8XD50SPM1JJH0E5CTXGDV5NJTKAKKR5V.sip013-transfer-many-trait'

[contracts.pox-delegation]
path = 'contracts/pox-delegation.clar'
clarity_version = 2
epoch = 2.1

[contracts.friedger-pool-delegation]
path = 'contracts/friedger-pool-delegation.clar'
clarity_version = 2
epoch = 2.1

[contracts.friedger-pool-sft]
path = 'contracts/friedger-pool-sft.clar'
clarity_version = 2
epoch = 2.1

[contracts.helper]
path = 'contracts/helper.clar'
clarity_version = 2
epoch = 2.1

[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
