[project]
name = 'clarity-stacking-pools'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'

[[project.requirements]]
contract_id = 'SP3C0TCQS0C0YY8E0V3EJ7V4X9571885D44M8EFWF.arkadiko-automation-trait-v1'

[[project.requirements]]
contract_id = 'SP21YTSM60CAY6D011EZVEVNKXVW8FVZE198XEFFP.pox-fast-pool-v2'

[contracts.pox4-self-service-multi]
path = 'contracts/pox4-self-service-multi.clar'
clarity_version = 2
epoch = 2.5
[contracts.payout-90-10-project]
path = 'contracts/payout/payout-90-10-project.clar'
clarity_version = 2
epoch = 2.5
